In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader

from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics

import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
from plotly.subplots import make_subplots
from collections import Counter

import pandas as pd
import numpy as np

import requests
import io

import matplotlib.pyplot as plt
import seaborn as sns
import math
import warnings

#這一行表示不希望看到警告訊息
warnings.filterwarnings(action='ignore')
#顯示中文
plt.rcParams['font.sans-serif']=['Microsoft YaHei']
plt.rcParams['axes.unicode_minus']=False

data = pd.read_csv("Heart_Tidy.csv")
data

,Unnamed: 0,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
912,913,45,M,TA,110,264.0,0,Normal,132,N,1.2,Flat,1
913,914,68,M,ASY,144,193.0,1,Normal,141,N,3.4,Flat,1
914,915,57,M,ASY,130,131.0,0,Normal,115,Y,1.2,Flat,1
915,916,57,F,ATA,130,236.0,0,LVH,174,N,0.0,Flat,1
916,917,38,M,NAP,138,175.0,0,Normal,173,N,0.0,Up,0